library("lme4"); library(tidyverse); data <- read_rds('Data/active/success-cleaned.rds')
ele_key <- read_csv("Data/active/elevation.csv") %>% select(UnCoor,elevation)
data <- left_join(x = data,y = ele_key,by = "UnCoor") %>% mutate(ele_scaled = c(scale(elevation)))
mod<-glmer(formula = at_least_one_success ~ Tmax_std_gridmet + Tmax_std_gridmet_sq + Tmax_std_gridmet * ele_scaled + Tmax_std_gridmet_sq * ele_scaled + pcpbefore_raw_gridmet + NLCD_p_forest + NLCD_p_human + NLCD_p_ag + substrate_binary + laydate_scaled + (1 | species) + (1 | year) + (1 | Region/UnCoor), data = filter(data,NewLU1 == "Human"), family = binomial(link = "logit"), control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05)))
write_rds(mod,"results/revisions/mainv1_elextemp_human.rds")
