## Data Dictionary: OneAttemptOneRow
## 
## Author: Katherine Lauck
## 
#rm(list=ls())
library(rio)
library(tidyverse)
load('../Data/raw-collapsed.RData')
#View(nest)

nlcd_vars=c("Total_500m","NLCD_open_water_500m","NLCD_ice_500m","NLCD_developed_open_500m","NLCD_developed_low_500m","NLCD_developed_medium_500m","NLCD_developed_high_500m","NLCD_barren_land_500m","NLCD_decidious_forest_500m","NLCD_evergreen_forest_500m",            
            "NLCD_mixed_forest_500m","NLCD_dwarf_shrub_500m","NLCD_shrub_500m","NLCD_grassland_500m" ,"NLCD_sedge_500m" ,"NLCD_lichens_500m", "NLCD_moss_500m","NLCD_pasture_500m","NLCD_cultivated_crops_500m","NLCD_woody_wetland_500m","NLCD_emergent_herbaceous_wetlands_500m",
            "NLCD_unkown_500m","Total_1km","NLCD_open_water_1km","NLCD_ice_1km","NLCD_developed_open_1km","NLCD_developed_low_1km","NLCD_developed_medium_1km","NLCD_developed_high_1km","NLCD_barren_land_1km","NLCD_decidious_forest_1km","NLCD_evergreen_forest_1km",            
            "NLCD_mixed_forest_1km","NLCD_dwarf_shrub_1km","NLCD_shrub_1km","NLCD_grassland_1km" ,"NLCD_sedge_1km" ,"NLCD_lichens_1km", "NLCD_moss_1km","NLCD_pasture_1km","NLCD_cultivated_crops_1km","NLCD_woody_wetland_1km","NLCD_emergent_herbaceous_wetlands_1km",
            "NLCD_unkown_1km","Total_2km","NLCD_open_water_2km","NLCD_ice_2km","NLCD_developed_open_2km","NLCD_developed_low_2km","NLCD_developed_medium_2km","NLCD_developed_high_2km","NLCD_barren_land_2km","NLCD_decidious_forest_2km","NLCD_evergreen_forest_2km",            
            "NLCD_mixed_forest_2km","NLCD_dwarf_shrub_2km","NLCD_shrub_2km","NLCD_grassland_2km" ,"NLCD_sedge_2km" ,"NLCD_lichens_2km", "NLCD_moss_2km","NLCD_pasture_2km","NLCD_cultivated_crops_2km","NLCD_woody_wetland_2km","NLCD_emergent_herbaceous_wetlands_2km",
            "NLCD_unkown_2km")

nlcd_values=c("numeric (m2)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)",
              "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)",
              "numeric (proportion)", "numeric (proportion)","numeric (m2)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)",
              "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)",
              "numeric (proportion)", "numeric (proportion)","numeric (m2)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)",
              "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)", "numeric (proportion)",
              "numeric (proportion)", "numeric (proportion)")

nlcd_descrip=c("Total area of 500m buffer","Proportion of the area of the National Land Cover Data class open water in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class ice in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed open in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed low in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed medium in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed high in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class barren land in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class decidious forest in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class evergreen forest in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class mixed forest in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class dwraf shrub in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class shrub in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class grassland in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class sedge in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class lichens in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class moss in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class pasture in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class cultivated crops in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class woody wetlands in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class emergent herbaceous wetlands in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class unknown in a buffer of 500m radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","total area of 1km buffer","Proportion of the area of the National Land Cover Data class open water in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class ice in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed open in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed low in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed medium in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed high in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class barren land in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class decidious forest in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class evergreen forest in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class mixed forest in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class dwraf shrub in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class shrub in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class grassland in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class sedge in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class lichens in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class moss in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class pasture in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class cultivated crops in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class woody wetlands in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class emergent herbaceous wetlands in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class unknown in a buffer of 1km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","total area of 2km buffer","Proportion of the area of the National Land Cover Data class open water in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class ice in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed open in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed low in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed medium in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class developed high in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class barren land in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class decidious forest in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class evergreen forest in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class mixed forest in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class dwraf shrub in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class shrub in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class grassland in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class sedge in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class lichens in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class moss in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class pasture in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class cultivated crops in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class woody wetlands in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class emergent herbaceous wetlands in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.","Proportion of the area of the National Land Cover Data class unknown in a buffer of 2km radii weighted by years available. Only 2001, 2004,2006, 2008, 2011, 2013 and 2016 are currently (October 2020) available  
               as resources to calculate the area of the different land uses. Data is expressed as a single value per year. To attribute a value to years in which NLCD is not available, values were weighted taken into account the values
               of the prior and posterior available data. For example, data for 2002 is calculated by adding 2/3 of the value for 2001 and 1/3 of the value for 2004. Data for Alaska is only available for the yeard 2001, 2011 and 2016.")

gridmet_vars=c("Tmin_raw","Tmin_anom","Tmin_std","Pcp45dAfter_raw","Pcp45dAfter_anom","Pcp45dAfter_std","Tmax_raw","Tmax_anom","Tmax_std","PcpBefore_raw","PcpBefore_anom","PcpBefore_std")
gridmet_description=c('The minimum of the minimum daily temperatures over the 45 days after the laydate, using  Gridmet','The minimum of the minimum daily temperatures over the 45 days after the laydate, minus the mean from 1980-2000,  using Gridmet','The minimum of the minimum daily temperatures over the 45 days after the laydate, minus the mean and divided by the standard deviation  from 1980-2000,  using Gridmet',
                 'The total precipitation over the 45 days after the laydate, using Gridmet','The total precipitation over the 45 days after the laydate, minus the mean from 1980-2000,  using Gridmet','The total precipitation over the 45 days after the laydate, minus the mean and divided by the standard deviation  from 1980-2000,  using Gridmet',
                 'The maximum of the maximum daily temperatures over the 45 days after the laydate, using  Gridmet','The maximum of the maximum daily temperatures over the 45 days after the laydate, minus the mean from 1980-2000,  using Gridmet','The maximum of the maximum daily temperatures over the 45 days after the laydate, minus the mean and divided by the standard deviation  from 1980-2000,  using Gridmet',
                 'The total precipitation over the 365 days before the laydate, using Gridmet','The total precipitation over the 365 days before the laydate, minus the mean from 1980-2000,  using Gridmet','The total precipitation over the 365 days before the laydate, minus the mean and divided by the standard deviation  from 1980-2000,  using Gridmet')
gridmet_values=c("Numeric (degrees Celcius)","Numeric","Numeric","Numeric (mm)","Numeric","Numeric","Numeric (degrees Celcius)","Numeric","Numeric","Numeric (mm)","Numeric","Numeric")

derived_gridmet_vars=c("Tmeanmax","Tstdmax_sp","Tmeanmin","Tstdmin_sp")
derived_gridmet_vars_description=c("The maximum of the maximum daily temperatures over the 45 days after the laydate, averaged across the years 1980-2000","The maximuum temperature of a site-date combination, relative to what the species usually experiences during nesting. To calculate, first calculate the maximum of the maximum daily temperatures over the 45 days after the laydate, averaged across the years 1980-2000. From this number, substract the mean and divide by the standard deviation of this metric across all other nesting attempts made by this species.","The minimum of the minimum daily temperatures over the 45 days after the laydate, averaged across the years 1980-2000","The minimum temperature of a site-date combination, relative to what the species usually experiences during nesting. To calculate, first calculate the minimum of the minimum daily temperatures over the 45 days after the laydate, averaged across the years 1980-2000. From this number, substract the mean and divide by the standard deviation of this metric across all other nesting attempts made by this species.")
derived_gridmet_vars_values=c("Numeric","Numeric","Numeric","Numeric")

dd <- tibble(Variable = c('attempt',gridmet_vars,"loc_id",'species','lat','lon','elevation','substrate','height','enter_orientation','habitat1','habitat2','outcome','year','laydate','hatchdate','total_young_fledged','perc_fledged','predation','at_least_one_failure','at_least_one_success','max_cowbird','cowbird_lgl','fail_cowbird',"Amatulli_Elevation",'LOC_ID_year',nlcd_vars,"Region200","Region250","UnCoor",derived_gridmet_vars),
             Description = c('Attempt number, as indicated in raw NestWatch data',gridmet_description,'Nest location ID as indicated in raw NestWatch data','Species abbreviation as indicated in raw NestWatch data','Latitude of nest location','Longitude of nest location','Elevation of nest location','Substrate of nest location as indicated in raw NestWatch data','Height of nest hole above the ground, as indicated in NestWatch data','Entrance orientation as indicated in raw NestWatch data','Immediate habitat within one meter of the nest','Dominant landscape type within 100 meters of the nest','Fate of the nest as indicated in raw NestWatch data','Year of attempt','Lay date of attempt. Either as indicated in raw NestWatch data or calculated if appropriate by subtracting # of eggs first observed from that observation date.','Hatch date of attempt. Either as indicated in raw NestWatch data or laydate + 14 if appropriate','Total number of young fledged','Percent of clutch size fledged','If the nest failed, was it caused by predation?','Did at least one young die?','Did at least one young fledge?','Maximum number of cowbird eggs or chicks observed','Were any cowbird eggs or young ever observed?','If the nest failed, was it caused by cowbirds?',"Elevation from Amatulli et al 2018","Unique identifier for a nest site location in a given year",nlcd_descrip,"Unique region identifier, where regions are defined by placing hexgrids across the study region, with 200 km between cells","Unique region identifier, where regions are defined by placing hexgrids across the study region, with 250 km between cells","Site identifier, constructed by combining the latitude and longitude of the site",derived_gridmet_vars_description),
             Values = c('Alpha/numeric',gridmet_values,"Alpha",'Alpha','Decimal degrees','Decimal degrees','Numeric','nesbox (Nest box/birdhouse), buildi (Building or dwelling), poptow (Post/Pole or platform), cliled (Cliff or rock ledge), ltrcav (Cavity in live tree branch), ssdtcv (Cavity in snag/dead tree), ssdtre (Dead tree branch), ltrbra (Live tree branch), busshr (Bush/shrub/cattails), ground (Ground), floveg (Floating vegetation), other (option to add comments)','Numeric','(N, S, E, W, NE, NW, SE, SW)','Agricultural Area, Human Modified, Woodland/Forest, Natural Grassland/Prairie, Chapparal/Shrubland, Desert Scrub, Fresh Water, Salt Water, Beach Tundra','Agricultural Area, Human Modified, Woodland/Forest, Natural Grassland/Prairie, Chapparal/Shrubland, Desert Scrub, Fresh Water, Salt Water, Beach Tundra','f (failure), f1 (all young found dead in or nearby nest), f2 (all young disappeared from nest before fledge date; reason unknown), f3 (predator known to cause nest failure), f4 (only cowbirds fledged), f5 (invasive species management), f6 (no eggs hatched), f7 (failure due to nest takeover by another bird), s (success), s1 (at least one host young fledged), u (unknown), u1 (unknown outcome), u2 (nest monitoring stopped prior to expected fledge data while nest was still active), u3 (no breeding behavior observed), i (inactive), n (not monitored)','Numeric','yyyy-mm-dd','yyyy-mm-dd','Numeric','Numeric','Logical (0 or 1)','Logical (0 or 1)','Logical (0 or 1)','Numeric','Logical (0 or 1)','Logical (0 or 1)',"Numeric (m, asl)","Alpha",nlcd_values,"Alpha","Alpha","Alpha",derived_gridmet_vars_values))

reorderDD=dd[match(colnames(nest),dd$Variable),]
# View(reorderDD)
# export(reorderDD,'Data/StreamlinedDataDictionary.xlsx')



