#!/bin/bash
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmax2laydate_LRT_AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmax2laydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmax2laydate2way.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmax2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmaxlaydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmin2laydate_LRT_AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmin2laydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmin2laydate2way.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/failure~stdmin2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~notemp_ag.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~notemp_forest.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~notemp_human.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~notemp_open.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax_ag.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax_forest.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax_human.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax_open.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2_ag.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2_forest.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2_human.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2_open.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2laydate_LRT_AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2laydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2laydate2way.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmax2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmaxlaydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmin2laydate_LRT_AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmin2laydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmin2laydate2way.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdmin2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q12/success~stdminlaydate2way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/failure~stdminsubstrate.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/failure~Substr_stdmaxlaydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/failure~Substr_stdmaxlaydateLRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/failure~Substr_stdminlaydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/failure~Substr_stdminlaydateLRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~cavity.tmax.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.ag.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.forest.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.ag.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.ag.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.for.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.forest.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.human.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.human.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.natop.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.laydate.natop.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxcavity.natop.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.ag.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.ag.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.for.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.forest.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.human.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.human.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.natop.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdmaxsubstrate.laydate.natop.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~stdminsubstrate.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~Substr_stdmaxAg.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~Substr_stdmaxForest.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~Substr_stdmaxhuman.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~Substr_stdmaxNatOp.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~Substr_stdminlaydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~Substr_stdminlaydateLRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~substrate.tmax.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q3/success~SubstrateStdmaxlaydate.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/controller-spatial-lrt.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/controller-spatial-nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/controller-spatial.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/failure~BBSstdmaxlaydate_LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/failure~BBSstdmaxlaydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/failure~BBSstdminlaydate_LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/failure~BBSstdminlaydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/failure~stdmaxbbs.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~BBSstdmax2laydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~BBSstdmaxlaydate_LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~BBSstdmaxlaydate_LRT2.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~BBSstdmaxlaydate_LRT3.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~BBSstdmaxlaydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~BBSstdmaxlaydate3way.LRT.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~Conscore.stdmax2laydate3way.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~Conscore.stdmaxlaydate3way.AK.LRT.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~ConScoreStdmaxlaydate_LRT2.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~ConScoreStdmaxlaydate_LRT3.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~stdmaxbbs.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~stdminbbs.AK.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tmean_rel2sp_anom_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tmean_rel2sp_anom_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tmean_rel2sp_z_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tmean_rel2sp_z_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tnestpd_meanmax_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tnestpd_meanmax_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tnestpd_stdmaxsp_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/success~tnestpd_stdmaxsp_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_tmaxsq.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_tmaxsq.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_tmaxsq.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_tmaxsq.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_tmaxsq.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_tmaxsq.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_nohot.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_noint.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_tmax.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_tmaxsq.sh
