#!/bin/bash
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tavgnestpd_meanmax_gridmet_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_anom_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tmean_rel2sp_z_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_meanmax_gridmet_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_anom_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_rel2sheard_z_Natural_open_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Ag_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Ag_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Forest_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Forest_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Human_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Human_3way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Natural_open_2way.sh
sbatch /home/kslauck/projects/nestwatch/Code/Analyses/q4/tnestpd_stdmaxsp_gridmet_Natural_open_3way.sh
